// AUTO-GENERATED by `npm run skin:import`. Do not edit manually.
// Re-run the importer or delete skin folders and re-run to regenerate.

import { sampleSkinDefinition } from "./components/imported/sample-skin/SampleSkin"

import type { AnyVisualComponentDefinition } from "./types"

export const IMPORTED_VISUAL_SKINS: AnyVisualComponentDefinition[] = [
    sampleSkinDefinition,
]
